### PR TITLE
Fix response in serving COM_FIELD_LIST

### PR DESCRIPTION
**Pull request by sundy-li**

### CODE REVIEW

**Comment by sundy-li** [comment]
https://dev.mysql.com/doc/internals/en/com-query-response.html#column-definition

```
if command was COM_FIELD_LIST {
lenenc_int     length of default-values
string[$len]   default values
```

**Comment by jonhoo** [comment]
I'm not quite sure I understand the change here, what it fixes, or what the implications of the comment in the source. Could you please elaborate a little?

**Comment by sundy-li** [comment]
Ok ，if the command is `Command::ListFields`,  then from the docs we should send default values to the MySQL client.

we just send NULL for simplicity, in MySQL protocol, It is 0xfb.

```
Protocol::MYSQL_TYPE_LONG_BLOB	0xfb	Implemented by ProtocolBinary::MYSQL_TYPE_LONG_BLOB
```

It was found by issue https://github.com/datafuselabs/datafuse/issues/567.

Also encounter this bug in  
https://github.com/ClickHouse/ClickHouse/blob/9f5cd35a6963cc556a51218b46b0754dcac7306a/src/Core/MySQL/PacketsProtocolText.cpp#L125-L130

**Comment by jonhoo** [comment]
Ah, I see. I'd prefer to have this actually do the right thing by using information from the `&Column` that's passed in. Maybe we could even augment to that to include the necessary data if it's currently missing? I'd also like to see a test added to capture the issue so that we don't introduce a regression again later!

**Comment by sundy-li** [comment]
> I'd prefer to have this actually do the right thing by using information from the &Column that's passed in
Do you mean to introduce a new field in `Column `, I tried it at first, but seems to have lots of codes to change to initialize the column.

>  I'd also like to see a test added to capture the issue so that we don't introduce a regression again later!

I'll try to add tests for this change.

**Comment by jonhoo** [comment]
> Do you mean to introduce a new field in `Column `, I tried it at first, but seems to have lots of codes to change to initialize the column.

Yup, exactly. Probably something like
```rust
default: Option<ValueInner<'static>>
```
It's true that you'd need to update some references to it though, and it would also be a breaking change, which is unfortunate. Given that we currently don't support `ListFields` really at all (it just returns a single column called "not implemented"), maybe the workaround you have here is okay for now after all. I do think we should fully implement the feature at some point, but we can do that elsewhere.

So, with all that said, let's at least get a test in place though, and then I'm happy to merge :)

**Comment by sundy-li** [comment]
I found it was a little hard to create unit tests for this feature. 

1. It has `it_handles_list_fields` test, but it was used for testing parsing COM_FIELD_LIST command.

2. `COM_FIELD_LIST`  is deprecated in mysql_common crate, so I can't mock this command in the unit test.   https://github.com/blackbeam/rust_mysql_common/blob/0bb22b3ee2edd581ae54ca21720cee0e712b13dc/src/packets/mod.rs#L126

**Comment by jonhoo** [comment]
Oh, that's interesting, I didn't know it was a legacy feature! I think it's okay to just implement it like this for now then, thanks :+1:

**Pull request merged**
